//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Vector2 p_lLRV_TranslateThrust;
        
        private static SteamVR_Action_Boolean p_lLRV_TranslateFire;
        
        private static SteamVR_Action_Boolean p_lLRV_GrabPinch;
        
        private static SteamVR_Action_Pose p_lLRV_Pose;
        
        private static SteamVR_Action_Boolean p_lLRV_FlipSwitch;
        
        public static SteamVR_Action_Vector2 lLRV_TranslateThrust
        {
            get
            {
                return SteamVR_Actions.p_lLRV_TranslateThrust.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean lLRV_TranslateFire
        {
            get
            {
                return SteamVR_Actions.p_lLRV_TranslateFire.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean lLRV_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_lLRV_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose lLRV_Pose
        {
            get
            {
                return SteamVR_Actions.p_lLRV_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean lLRV_FlipSwitch
        {
            get
            {
                return SteamVR_Actions.p_lLRV_FlipSwitch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.lLRV_TranslateThrust,
                    SteamVR_Actions.lLRV_TranslateFire,
                    SteamVR_Actions.lLRV_GrabPinch,
                    SteamVR_Actions.lLRV_Pose,
                    SteamVR_Actions.lLRV_FlipSwitch};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.lLRV_TranslateThrust,
                    SteamVR_Actions.lLRV_TranslateFire,
                    SteamVR_Actions.lLRV_GrabPinch,
                    SteamVR_Actions.lLRV_Pose,
                    SteamVR_Actions.lLRV_FlipSwitch};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.lLRV_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.lLRV_TranslateFire,
                    SteamVR_Actions.lLRV_GrabPinch,
                    SteamVR_Actions.lLRV_FlipSwitch};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.lLRV_TranslateThrust};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.lLRV_TranslateThrust,
                    SteamVR_Actions.lLRV_TranslateFire,
                    SteamVR_Actions.lLRV_GrabPinch,
                    SteamVR_Actions.lLRV_FlipSwitch};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_lLRV_TranslateThrust = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/LLRV/in/TranslateThrust")));
            SteamVR_Actions.p_lLRV_TranslateFire = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/LLRV/in/TranslateFire")));
            SteamVR_Actions.p_lLRV_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/LLRV/in/GrabPinch")));
            SteamVR_Actions.p_lLRV_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/LLRV/in/Pose")));
            SteamVR_Actions.p_lLRV_FlipSwitch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/LLRV/in/FlipSwitch")));
        }
    }
}
