//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_LLRV : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 TranslateThrust
        {
            get
            {
                return SteamVR_Actions.lLRV_TranslateThrust;
            }
        }
        
        public virtual SteamVR_Action_Boolean TranslateFire
        {
            get
            {
                return SteamVR_Actions.lLRV_TranslateFire;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.lLRV_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.lLRV_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean FlipSwitch
        {
            get
            {
                return SteamVR_Actions.lLRV_FlipSwitch;
            }
        }
    }
}
